### ISSUE TITLE
Unresolved references for `licenseUrl` & `sourceCodeUrl`

### ISSUE THREAD

**Issue by sgoudham** [JetBrains/fleet-theme-plugin-template#1]
Hey :wave:,

We're [currently going through the efforts](https://github.com/catppuccin/fleet/pull/24) of publishing [catppuccin/fleet](https://github.com/catppuccin/fleet) to the new Fleet Theme Plugin Marketplace. We've cloned this template and added in the necessary information, however, after uncommenting the following `publishing` block:

https://github.com/JetBrains/fleet-theme-plugin-template/blob/d66ce3557a05727f46c0e86f83421e65eb84f109/my-theme-plugin/build.gradle.kts#L24-L28

We're getting this error when running `./gradlew distZip`:

```shell
Calculating task graph as no cached configuration is available for tasks: distZip

> Configure project :plugin
e: file:///home/hammy/Catppuccin/fleet/plugin/build.gradle.kts:31:9: Unresolved reference: licenseUrl
e: file:///home/hammy/Catppuccin/fleet/plugin/build.gradle.kts:32:9: Unresolved reference: sourceCodeUrl

FAILURE: Build failed with an exception.

* Where:
Build file '/home/hammy/Catppuccin/fleet/plugin/build.gradle.kts' line: 31

* What went wrong:
Script compilation errors:

  Line 31:         licenseUrl = "https://github.com/catppuccin/fleet/blob/main/LICENSE"
                   ^ Unresolved reference: licenseUrl

  Line 32:         sourceCodeUrl = "https://github.com/catppuccin/fleet"
                   ^ Unresolved reference: sourceCodeUrl

2 errors
```

I'd appreciate if someone could help me understand why these URLs are unresolved references and/or clarify what URLs should be used instead. (Are these values not valid for the first publish and should only be included after it's on the marketplace?)

Thanks!

**Comment by ArchangelX360** [comment]
Hey, sorry about that, please do not set any value.

These are old DSL leftover, I'll fix the template right away.
