### ISSUE TITLE
Allow running distZip without a marketplace token

### ISSUE THREAD

**Issue by davfsa** [JetBrains/fleet-theme-plugin-template#2]
Hello!

I was wondering if it would be possible making `distZip` not require a token to be run. I understand `upload` being gated behind a token, but I found it surprising that `distZip` was too.

Thanks for the first public release of the SDK, hope to see it keep improving!

Edit: Sorry if this is not the right repository to ask for this! I can repost it in the correct one if needed :)

**Comment by ArchangelX360** [comment]
Hello, the token is required to retrieve your vendor ID.

Alternatively, not to require a token, you should be able to specify:
```kotlin
fleetPlugin {
    publishing {
         vendorId = "your-vendor-id-here"
    }
}
```
and that should be enough to resolve all the information needed by `distZip`.

EDIT: I tried it out, and indeed it works as explained.

EDIT2: to know what is your vendor ID, go to https://plugins.jetbrains.com/author/me and check the URL of `vendor profile` link:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/25cdfc2b-3339-480f-bcf2-716aede5d8ba">
